service: sls-auction-service

plugins:
  - serverless-bundle 

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  bundle:
    linting: false # Setting 'flase' for tutorial purposes only. Enable it if needed for Production. 