service: sls-auction-service

plugins:
  - serverless-bundle 

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iam:
    role:
      statements:
        - ${file(./iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  # iam:
  #   role:
  #     statements:
  #       - Effect: 'Allow'
  #         Action: 
  #           - dynamodb:PutItem
  #         Resource: 
  #           - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/AuctionsTable

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

resources:
  Resources:
    AuctionsTable: ${file(./resources/AuctionsTable.yml):AuctionsTable}
    # AuctionsTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: AuctionsTable
    #     BillingMode: PAY_PER_REQUEST
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: false # Setting 'false' for tutorial purposes only. Enable it if needed for Production. 